// Copyright 2021 Manna Harbour
// https://github.com/manna-harbour/miryoku

#define ZMK_MOUSE_DEFAULT_MOVE_VAL 1200  // 600
#define ZMK_MOUSE_DEFAULT_SCRL_VAL 20    // 10

#define MIRYOKU_CLIPBOARD_MAC
#define CONFIG_ZMK_IDLE_SLEEP_TIMEOUT 3600000
#define CONFIG_ZMK_SLEEP
#define CONFIG_WS2812_STRIP
#define CONFIG_ZMK_RGB_UNDERGLOW
#define CONFIG_ZMK_RGB_UNDERGLOW_ON_START
#define CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE
#define CONFIG_ZMK_RGB_UNDERGLOW_HUE_START 160
#define CONFIG_ZMK_RGB_UNDERGLOW_EFF_START 3
#define CONFIG_EC11
#define CONFIG_EC11_TRIGGER_GLOBAL_THREAD
#define CONFIG_ZMK_MOUSE
#define CONFIG_ZMK_BACKLIGHT
#define CONFIG_ZMK_BACKLIGHT_BRT_START 100
