# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "00 zmb corne colemakdhk"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["eyelash_corne_left", "eyelash_corne_right"]'
      shield: '["nice_view"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR", "#define MIRYOKU_CLIPBOARD=MAC"]'
      alphas: '["colemakdhk"]'
      branches: '["zmkfirmware/zmk/main", "zambo/zmk-corne/start"]'
